# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_server/notifications.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_server/notifications.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fgrpc_server/notifications.proto\x12\x0bgrpc_server\"\x9e\x01\n\x13NotificationRequest\x12\x14\n\x0crecipient_id\x18\x01 \x01(\x05\x12\x19\n\x11notification_type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x1b\n\x13related_object_type\x18\x05 \x01(\t\x12\x19\n\x11related_object_id\x18\x06 \x01(\x05\"Q\n\x14NotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0fnotification_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2p\n\x13NotificationService\x12Y\n\x10SendNotification\x12 .grpc_server.NotificationRequest\x1a!.grpc_server.NotificationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server.notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONREQUEST']._serialized_start=49
  _globals['_NOTIFICATIONREQUEST']._serialized_end=207
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=209
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=290
  _globals['_NOTIFICATIONSERVICE']._serialized_start=292
  _globals['_NOTIFICATIONSERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
